name: neuromorphic-har

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - numpy
  - matplotlib
  - scikit-learn
  - einops