from typing import Dict, Optional, Tuple, Union

import numpy as np


ArrayLike = Union[float, np.ndarray]


__all__ = [
    "default_step_from_std",
    "sigma_delta",
    "level_crossing",
]


def default_step_from_std(x: np.ndarray, k: float = 0.1, eps: float = 1e-6) -> np.ndarray:
    """Compute a per-channel step from the signal standard deviation."""
    x = np.asarray(x, dtype=np.float32)
    if x.ndim != 2:
        raise ValueError("x must have shape [T, C]")

    sd = x.std(axis=0)
    return np.maximum(eps, k * sd).astype(np.float32)


def _as_vec(v: ArrayLike, c: int, name: str) -> np.ndarray:
    """Convert a scalar or channel vector to float32."""
    y = np.asarray(v, dtype=np.float32)
    if y.ndim == 0:
        return np.full((c,), float(y), dtype=np.float32)
    if y.shape != (c,):
        raise ValueError(f"{name} must be a scalar or a vector with shape [C]")
    return y


def sigma_delta(
    x: np.ndarray,
    theta: ArrayLike,
    init: str = "x0",
    return_reconstruction: bool = True,
    dead_zone: Optional[ArrayLike] = None,
) -> Tuple[np.ndarray, Dict[str, np.ndarray], Optional[np.ndarray]]:
    """
    Encode a contiguous signal with sigma-delta events.

    Parameters
    ----------
    x:
        Input signal with shape [T, C].
    theta:
        Reconstruction step, either scalar or one value per channel.
    init:
        Initial reconstruction mode: "x0" or "zero".
    return_reconstruction:
        If True, return the reconstruction trace.
    dead_zone:
        Optional threshold before firing. A scalar is treated as a factor of theta;
        a vector is treated as an absolute per-channel threshold.

    Returns
    -------
    events:
        Event tensor with shape [T, C, 2], where [:, :, 0] is up and [:, :, 1] is down.
    state:
        Dictionary containing the last reconstruction value.
    rec:
        Reconstruction trace with shape [T, C], or None.
    """
    x = np.asarray(x, dtype=np.float32)
    if x.ndim != 2:
        raise ValueError("x must have shape [T, C]")

    t_len, c = x.shape
    th = _as_vec(theta, c, "theta")
    if np.any(th <= 0.0):
        raise ValueError("theta must be positive")

    # Threshold setup
    if dead_zone is None:
        dz = np.zeros((c,), dtype=np.float32)
    else:
        dz = np.asarray(dead_zone, dtype=np.float32)
        if dz.ndim == 0:
            dz = dz * th
        elif dz.shape != (c,):
            raise ValueError("dead_zone must be None, a scalar, or a vector with shape [C]")
        if np.any(dz < 0.0):
            raise ValueError("dead_zone must be non-negative")

    # State initialization
    if init == "x0":
        xh = x[0].copy()
    elif init == "zero":
        xh = np.zeros((c,), dtype=np.float32)
    else:
        raise ValueError('init must be "x0" or "zero"')

    ev = np.zeros((t_len, c, 2), dtype=np.uint8)
    rec = np.empty((t_len, c), dtype=np.float32) if return_reconstruction else None

    # Temporal encoding
    for t in range(t_len):
        dx = x[t] - xh
        m = np.abs(dx) > dz

        y = np.zeros((c,), dtype=np.int8)
        y[m] = np.where(dx[m] >= 0.0, 1, -1).astype(np.int8)

        ev[t, :, 0] = y == 1
        ev[t, :, 1] = y == -1

        xh = xh + y.astype(np.float32) * th

        if rec is not None:
            rec[t] = xh

    st = {"xhat": xh.copy()}
    return ev, st, rec


def level_crossing( #Not implemented in the paper
    x: np.ndarray,
    delta: ArrayLike,
    init: str = "x0",
    max_crossings_per_sample: Optional[int] = 15,
    return_level_trace: bool = False,
) -> Tuple[np.ndarray, Dict[str, np.ndarray], Optional[np.ndarray]]:
    """
    Encode a contiguous signal with level-crossing events.

    Parameters
    ----------
    x:
        Input signal with shape [T, C].
    delta:
        Level step, either scalar or one value per channel.
    init:
        Initial level mode: "x0" or "zero".
    max_crossings_per_sample:
        Optional cap for events generated by one sample and channel.
    return_level_trace:
        If True, return the level trace.

    Returns
    -------
    events:
        Event tensor with shape [T, C, 2], where [:, :, 0] is up and [:, :, 1] is down.
    state:
        Dictionary containing the last level value.
    level_trace:
        Level trace with shape [T, C], or None.
    """
    x = np.asarray(x, dtype=np.float32)
    if x.ndim != 2:
        raise ValueError("x must have shape [T, C]")

    t_len, c = x.shape
    dv = _as_vec(delta, c, "delta")
    if np.any(dv <= 0.0):
        raise ValueError("delta must be positive")

    if max_crossings_per_sample is not None and max_crossings_per_sample < 0:
        raise ValueError("max_crossings_per_sample must be non-negative or None")

    # State initialization
    if init == "x0":
        lv = x[0].copy()
    elif init == "zero":
        lv = np.zeros((c,), dtype=np.float32)
    else:
        raise ValueError('init must be "x0" or "zero"')

    ev = np.zeros((t_len, c, 2), dtype=np.uint8)
    tr = np.empty((t_len, c), dtype=np.float32) if return_level_trace else None

    # Temporal encoding
    for t in range(t_len):
        df = x[t] - lv

        up = np.floor(np.maximum(df, 0.0) / dv)
        dn = np.floor(np.maximum(-df, 0.0) / dv)

        if max_crossings_per_sample is not None:
            up = np.minimum(up, max_crossings_per_sample)
            dn = np.minimum(dn, max_crossings_per_sample)

        ev[t, :, 0] = up.astype(np.uint8)
        ev[t, :, 1] = dn.astype(np.uint8)

        lv = lv + (up - dn) * dv

        if tr is not None:
            tr[t] = lv

    st = {"level": lv.copy()}
    return ev, st, tr
